[user]
name = "motikix"
email = "25551031+motikix@users.noreply.github.com"

[working-copy]
eol-conversion = "none"

[ui]
default-command = ["status", "--no-pager"]
diff-formatter = ["difft", "--color=always", "$left", "$right"]
